### ISSUE TITLE
How to disable unwanted animation in the overlay ?

### ISSUE THREAD

**Issue by nashfive** [faberNovel/DynamicOverlay#14]
Hi there! Pretty cool component! I am trying to use it in my app and it works pretty well.. I only have an issue with animations that happen automatically within the overlay content...
For example, if I have a scrollable `LazyVStack` in the overlay, dragging the overlay to expand it will add more items in the `ScrollView` (I guess it happens since the frame of the scrollable content is expanded as well), but it seems that an animation is applied but it doesn't look great :( 
Do you think it's coming from the component itself or from the DynamicContainer lib ? 

here is a small demo to illustrate the issue: 
```swift
import SwiftUI
import DynamicOverlay

struct Demo: View {
    enum Notch: Equatable, CaseIterable { case min, max }

    @State private var strings = Array(0...1000).map { "Item \($0)" }

    var body: some View {
        Color.blue
            .dynamicOverlay(overlay)
            .dynamicOverlayBehavior(behavior)
    }
    
    var overlay: some View {
        VStack(spacing: 0) {
            Text("Drag me")
                .frame(maxWidth: .infinity).frame(height: 44)
                .background(Color.yellow)
                .draggable()
            
            ScrollView {
                LazyVStack(spacing: 0) {
                    ForEach(strings, id: \.self) { string in
                        VStack(spacing: 0) {
                            Text(string).frame(height: 44)
                            Divider()
                        }
                    }
                }
                .frame(maxWidth: .infinity)
            }
        }
        .background(Color.white)
    }
    
    var behavior: some DynamicOverlayBehavior {
        MagneticNotchOverlayBehavior<Notch> { notch in
            switch notch {
            case .min: return .fractional(0.15)
            case .max: return .fractional(0.95)
            }
        }
    }
}
```
When the overlay is dragged up for the first time, the newly instantiated list items are added with an animation. I noticed this animation is also applied with a more complex overlay content (replacing its UI with other components, etc).

**Comment by gaetanzanella** [comment]
Hi @nashfive, the issue is fixed in beta 8. Thanks for the example!
