### ISSUE TITLE
drivingScrollView() with more than one scrollview in the overlay content ?

### ISSUE THREAD

**Issue by nashfive** [faberNovel/DynamicOverlay#16]
Hi :) 
I love the `.drivingScrollView()` feature, but unfortunately, it doesn't support views with more than one scrollview. For example, my overlay content is a VStack of 2 scrollViews: a horizontal scroll for my filters, and a vertical one for the filtered results. Without the horizontal scroll, it works well. I guess the scrollview detection is taking the first one in the view hierarchy :(  If I put the horizontal scrollview *after* the vertical one, then the driving feature works as expected. 
 
Would there be a way to specify in the content which scrollview can drive the overlay drag gesture? (with something like Inspect), or is there a "trick" to force the drivingScrollView to a specific scrollview?

**Comment by gaetanzanella** [comment]
I know 😔 . There is a branch for [that](https://github.com/faberNovel/DynamicOverlay/tree/feature/improve-driving-scroll-view) but it is not ready yet. It is not trivial. 

The only workaround would be to search for the overlay container and the target scroll view inside the hierarchy and set the `drivingScrollView` by hand.

**Comment by nashfive** [comment]
Bummer.. 😞 I guess I'll go with that limitation for the time being. 
Also I think implementing a custom drag gesture instead of using an horizontal ScrollView might work but at the expense of the native scrollview UX. 
Feel free to close that issue if you prefer.

**Comment by kushsolitary** [comment]
> I know 😔 . There is a branch for [that](https://github.com/faberNovel/DynamicOverlay/tree/feature/improve-driving-scroll-view) but it is not ready yet. It is not trivial.
> 
> The only workaround would be to search for the overlay container and the target scroll view inside the hierarchy and set the `drivingScrollView` of the container by hand.

Hello,

is there any update on this issue? I recently faced the same and tried the branch you mentioned but unfortunately, it didn't work.

**Comment by Lumentus** [comment]
@gaetanzanella I have just now created a PR with a possible solution for this problem. See PR #26
