### ISSUE TITLE
Animation issue when both the overlay's behavior & content are programmatically updated

### ISSUE THREAD

**Issue by nashfive** [faberNovel/DynamicOverlay#18]
Hi @gaetanzanella,

I've found another potential issue related to the overlay's animation system when trying to update both the overlay's content and behavior programmatically.
To demonstrate the issue, I have setup a simple use case:
I want to display 2 different contents in the overlay and change the notch behavior based on the content. 

Here is a simple view to illustrate this (there is only one notch with an absolute value for simplicity) : 

```swift
import SwiftUI
import DynamicOverlay

enum Notch: CaseIterable, Equatable { case min }

struct ContentView: View {
    @State var notch: Notch = .min
    @State var showContent2 = false
    
    var body: some View {
        Color.white
            .dynamicOverlay(overlayView)
            .dynamicOverlayBehavior(behavior)
    }
    
    private var behavior: some DynamicOverlayBehavior {
        MagneticNotchOverlayBehavior<Notch> { _ in .absolute(showContent2 ? 400 : 200) }
    }
    
    private var overlayView: some View {
        VStack(spacing: 0) {
            Color.blue.frame(height: 50).draggable()
            if showContent2 {
                OverlayContent(title: "Content 2", color: Color.yellow, action: { showContent2.toggle() })
            } else {
                OverlayContent(title: "Content 1", color: Color.red, action: { showContent2.toggle() })
            }
        }
    }
}

struct OverlayContent: View {
    let title: String
    let color: Color
    let action: () -> Void
    
    var body: some View {
        ZStack(alignment: .top) {
            color
            VStack {
                Text(title).font(.title)
                Button(action: action, label: { Text("Action") }).padding()
            }
        }
    }
}
```

As you can see, when I toggle my State, the content of the overlay and the behavior are changed. 
As a result, when I tap the "Action" button, it slides the overlay to its new position and creates a new `OverlayContent` view. Apparently, in this case, this new view is implicitely animated by SwiftUI animation system (cf the video I've attached). 
It works correctly if I don't creating a new `OverlayContent` and pass conditional parameters, but it's not really applicable for real use cases (i.e. displaying very different content)

https://user-images.githubusercontent.com/50933/123657539-2aeb6880-d831-11eb-9350-5e2889b148df.mp4

Any idea where the issue could be ? SwiftUI ? DynamicOverlay ? OverlayContainer ?

**Comment by nashfive** [comment]
@gaetanzanella have you given a look to this by any chance ?

**Comment by gaetanzanella** [comment]
Hi @nashfive, I tried a fix ! 

Could you try in your project using [this branch](https://github.com/faberNovel/DynamicOverlay/tree/feature/layout-invalidation-fix) and tell me the result?

**Comment by gaetanzanella** [comment]
Notice that you now have to explicitly tell the overlay to animate the layout change:

```swift
    private var overlayView: some View {
        VStack(spacing: 0) {
            Color.blue.frame(height: 50).draggable()
            if showContent2 {
                OverlayContent(title: "Content 2", color: Color.yellow, action: { withAnimation { showContent2.toggle() }}) // animated
            } else {
                OverlayContent(title: "Content 1", color: Color.red, action: { showContent2.toggle() }) // not animated
            }
        }
    }
```

**Comment by nashfive** [comment]
@gaetanzanella Sorry I haven't had the time to check this yet. I'll check again with your branch today :)

**Comment by gaetanzanella** [comment]
Yes, you can try with 1.0.0-beta.9!

**Comment by nashfive** [comment]
@gaetanzanella Perfect it works really well now with the beta 9 ! Thanks for your work 👍🏻
