### ISSUE TITLE
Disable scrolling while dragging the scroll view

### ISSUE THREAD

**Issue by chrs1885** [faberNovel/DynamicOverlay#35]
Using the `.drivingScrollView()` modifier lets the user drag the overlay towards the bottom by scrolling the contained scroll view. 👍 

However, while scrolling down the user can still scroll up again, which causes a change of the scroll offset. Is there a way to disable scrolling while dragging the overlay?

**Comment by gaetanzanella** [comment]
Hi @chrs1885,

The dragging of the overlay depends on various conditions:
- If I scroll up, the overlay moves up
- If I scroll down and the scroll content is at its initial position, the overlay moves down
- If I scroll down and the scroll content is not at its initial position, it scrolls until reaching its initial position

Which condition would you like to change?

**Comment by chrs1885** [comment]
Hi, I guess no. 2. 

1. Drag view to fullscreen
2. Scroll down (-> drags the view towards the bottom) AND up again (scrolls the list)

**Comment by gaetanzanella** [comment]
[Here](https://github.com/applidium/OverlayContainer/blob/master/Assets/scroll.gif) is a video that shows how the overlay behaves. Is it the case in your project?

**Comment by chrs1885** [comment]
It is, however I'd like to disable scrolling entirely as long as the .max position hasn't been reached. The "Find my" app is a good example: In order to scroll the view the user needs to drag the view to the .max position. 

https://user-images.githubusercontent.com/1390908/170709791-696ea2bf-6bf2-43d3-9338-3c47a5631f84.mp4
