### ISSUE TITLE
Jumping animation issue.

### ISSUE THREAD

**Issue by ZefsAl** [faberNovel/DynamicOverlay#42]
When "Overlay" appears, a space appears at the bottom. (Jumps out too much)
How can I interact with the animation to change it to something else.

https://user-images.githubusercontent.com/97045435/180496185-20cc5461-5d67-46dd-9993-8008ce5f9f6f.MP4

**Comment by gaetanzanella** [comment]
Thanks for the issue @ZefsAl! Interesting. 

You can modify the method:
```
public func animation(using context: OverlayContainerTransitionCoordinatorContext) -> Animation?
```
in `DynamicOverlayContainerAnimationController.swift` but it is inside the library. 

Could you propose new values and do a PR? 🙏🏻

**Comment by zoujunvolvo** [comment]
is any one fix this?

**Comment by gaetanzanella** [comment]
@zoujunvolvo the new release v1.0.2 should help :)

**Comment by zoujunvolvo** [comment]
@gaetanzanella  Thank you
