### ISSUE TITLE
Memory leak after every presentation of dynamic overlay

### ISSUE THREAD

**Issue by nashfive** [faberNovel/DynamicOverlay#43]
I found that every time the overlay is presented, it creates objects that will stay in memory forever because of cyclic references.
Even a simple project (see below) with nothing special will exhibit the issue. 
After showing/dismissing 5 times a fullscreen cover and dismissing it, I have 5 leaks:

![Screenshot 2022-11-10 at 11 08 02](https://user-images.githubusercontent.com/50933/201062527-5903ff58-75b9-4526-964c-96f20edc315b.jpg)

---

Code used : 

```swift
import SwiftUI
import DynamicOverlay

struct ContentView: View {
    @State private var showCover = false
    var body: some View {
        Button("Open") {
            showCover = true
        }
        .fullScreenCover(isPresented: $showCover) {
            Cover().ignoresSafeArea()
        }
    }
}

enum Notch: CaseIterable, Equatable { case min, max }

struct Cover: View {
    @State private var notch = Notch.min
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        Color.blue
            .ignoresSafeArea()
            .onTapGesture(perform: dismiss.callAsFunction)
            .dynamicOverlayBehavior(behavior)
            .dynamicOverlay(Color.yellow)

    }

    private var behavior: some DynamicOverlayBehavior {
        MagneticNotchOverlayBehavior<Notch> {
            $0 == .min ? .absolute(200) : .fractional(0.9)
        }
        .notchChange($notch)
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

```

**Comment by nashfive** [comment]
@gaetanzanella Should I report it in the OverlayContainer project as well?

**Comment by nashfive** [comment]
@gaetanzanella I am using the latest version: 1.0.0 (with OverlayContainer 3.5.2)

**Comment by nashfive** [comment]
@gaetanzanella Thanks for taking care of that issue so quickly! Any idea on when it will be released ?

**Comment by gaetanzanella** [comment]
I have ci issues since Xcode 14… It should be fix soon still

**Comment by gaetanzanella** [comment]
@nashfive version 1.0.1 available 🥵🙂
